<?php
/**
 * StoreFront Bazaarvoice Extension for Magento
 *
 * PHP Version 5
 *
 * LICENSE: This source file is subject to commercial source code license
 * of StoreFront Consulting, Inc.
 *
 * @category  SFC
 * @package   Bazaarvoice_Ext
 * @author    Dennis Rogers <dennis@storefrontconsulting.com>
 * @copyright 2016 StoreFront Consulting, Inc
 * @license   http://www.storefrontconsulting.com/media/downloads/ExtensionLicense.pdf StoreFront Consulting Commercial License
 * @link      http://www.StoreFrontConsulting.com/bazaarvoice-extension/
 */
?>
<?php /** @var Bazaarvoice\Connector\Block\Product $this */ ?>

<?php if ($this->isEnabled()): ?>
    <!--suppress ALL -->
    <script type="text/javascript">
        var bvConfigData = {};
<?php if ($this->getProductId()) : ?>
        bvConfigData.productId = "<?php echo $this->getProductSku() ?>";
<?php endif; ?>
        $BV.configure("global", bvConfigData);
    </script>
<?php if ($this->isConfigurable()): ?>
    <script type="text/javascript">
        var bvChildren = <?php echo $this->getChildrenJson(); ?>;
        var bvSelected = "<?php echo $this->getProductSku() ?>";
    </script>
<?php endif; ?>

<?php endif;
